### PR TITLE
added alerts, added update book logic, details logic, etc

### PR DESCRIPTION
**Pull request by okikiolanlesi**
added alerts, added update book logic, details logic, not found page etc.
Still waiting on the backend so i can make api calls for content and auth.

### CODE REVIEW

**Comment by adeniranjohn** [comment]
Kindly check your push. 
There is a conflict.

**Review by Teejay128 — APPROVED** [review]
Thanks for this boss

I would also really appreciate if you could update the readme on how to run the react project locally, for anyone that may want to view the project in action

**Comment by okikiolanlesi** [comment]
The readme.md in the react project already explains all the available scripts,

**Comment by okikiolanlesi** [comment]
> Thanks for this boss
> 
> I would also really appreciate if you could update the readme on how to run the react project locally, for anyone that may want to view the project in action

cd into the frontend folder and run 'npm start'

**Pull request merged**
